n = str(input('Digite  seu nome commpleto...')).strip()
nome = n.split()
print('Prazer em conhecer!')
print('Seu primeiro nome é...{}' .format(nome[0]))
print('Seu ultimo nome é...{}' .format(nome[len(nome)-1]))